name: Base Styles
description: Base styles for the Savannah theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Base Background
      default: "#ffffff"
    border-color:
      type: input.colorpicker
      label: border Color
      default: "#e0e0e5"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#424753"
    text-color-alt:
      type: input.colorpicker
      label: Base Alt Text Color
      default: "#999999"
    favicon:
       type: input.imagepicker
       label: Favicon
       filter: '.(jpe?g|gif|png|svg|ico)$'
