name: home_-_particles
timestamp: 1480534388
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1472319055
positions: {  }
sections:
  intro: Intro
  expandable: Expandable
  navigation: Navigation
  features: Features
  quote: Quote
  utility: Utility
  above: Above
  expandable2: Expandable2
  expanded: Expanded
  testimonials: Testimonials
  portfolio: Portfolio
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-5989: 'Hire Me'
    custom-9276: 'Custom HTML'
    custom-3119: Features
    custom-2861: 'Custom HTML'
    custom-6100: 'Custom HTML'
    custom-4505: 'Custom HTML'
    custom-5623: 'Custom HTML'
    custom-6556: 'Contact Form'
  social:
    social-9576: Social
    social-3503: Social
  hero:
    hero-7272: 'Hero Banner'
  menu:
    menu-6409: Menu
  sectiontitle:
    sectiontitle-6366: 'Section Title'
    sectiontitle-1332: 'MY SKILLS'
    sectiontitle-8251: 'WORK & EDUCATION'
    sectiontitle-8933: 'Section Title'
    sectiontitle-7871: 'Section Title'
    sectiontitle-9392: Contact
  bio-info:
    bio-info-1264: 'Bio Stats'
  skillbar:
    skillbar-5033: 'Skill Bar Graph'
    skillbar-4987: 'Skill Bar Graph'
  numcounter:
    numcounter-9571: 'Quick Stats'
  resumedl:
    resumedl-6742: 'Download Resume'
  timeline:
    timeline-6465: Timeline
    timeline-6997: Timeline
  owlcarousel:
    owlcarousel-7560: 'Owl Carousel'
  spacer:
    spacer-9583: Spacer
    spacer-1143: Spacer
    spacer-6966: Spacer
    spacer-9951: Spacer
  portfolio:
    portfolio-3037: Portfolio
    portfolio-2986: Portfolio
    portfolio-8825: Portfolio
    portfolio-8584: Portfolio
    portfolio-1558: Portfolio
    portfolio-1079: Portfolio
  googlemap:
    googlemap-1641: 'Google Map'
  totop:
    totop-8670: 'To Top'
  branding:
    branding-9914: Branding
  copyright:
    copyright-1736: Copyright
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit:
  default:
    custom-5989: custom-5107
    social-9576: social-3896
