name: home_-_particles
timestamp: 1479150794
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1472319055
positions: {  }
sections:
  intro: Intro
  navigation: Navigation
  features: Features
  utility: Utility
  above: Above
  expanded: Expanded
  testimonials: Testimonials
  protfolio: Protfolio
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-5989: 'Hire Me'
    custom-7395: 'Custom HTML'
    custom-9601: 'Custom HTML'
    custom-3119: Features
    custom-6355: 'Develop CMS themes quickly'
    custom-7658: 'Customer Testimonials'
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  menu:
    menu-6409: Menu
    menu-1596: Menu
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  logo:
    logo-9571: 'Logo / Image'
  copyright:
    copyright-1736: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit:
  default:
    intro: intro
    custom-5989: custom-5107
    custom-7395: custom-7143
