version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1472319055
layout:
  /intro/:
    -
      - 'custom-5989 50'
      - 'social-9576 50'
  /expandable/:
    -
      - custom-9276
  /header/:
    -
      - hero-7272
  /navigation/:
    -
      - menu-6409
  /features/:
    -
      - sectiontitle-6366
    -
      - 'bio-9275 70'
      - 'bio-info-1264 30'
  /quote/:
    -
      - quote-7312
  /utility/:
    -
      - sectiontitle-1332
    -
      - 'skillbar-5033 33.3'
      - 'skillbar-4987 33.3'
      - 'numcounter-9571 33.3'
  /above/:
    -
      - resumedl-6742
  /expandable2/:
    -
      - custom-5623
  /expanded/:
    -
      - sectiontitle-8251
    -
      - 'timeline-6465 50'
      - 'timeline-6997 50'
  /testimonials/:
    -
      - sectiontitle-8933
    -
      - owlcarousel-7560
  /portfolio/:
    -
      - sectiontitle-7871
    -
      - 'spacer-9583 14'
      - 'portfolio-3037 24'
      - 'portfolio-2986 24'
      - 'portfolio-8825 24'
      - 'spacer-1143 14'
    -
      - 'spacer-6966 14'
      - 'portfolio-8584 24'
      - 'portfolio-1558 24'
      - 'portfolio-1079 24'
      - 'spacer-9951 14'
  /quote2/:
    -
      - quote-9281
  /container-main/:
    -
      -
        'mainbar 80':
          -
            - sectiontitle-9392
          -
            - 'googlemap-1641 50'
            - 'custom-6556 50'
      -
        'sidebar 20': {  }
  /footer/:
    -
      - totop-8670
    -
      - branding-9914
    -
      - social-3503
    -
      - copyright-1736
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
  expandable:
    type: section
    attributes:
      boxed: '2'
      class: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  navigation:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  quote:
    type: section
    attributes:
      boxed: '2'
      class: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: '2'
      class: ''
  expandable2:
    type: section
    attributes:
      boxed: '2'
      class: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  quote2:
    type: section
    title: 'Second Quote'
    attributes:
      boxed: '2'
      class: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  custom-5989:
    title: 'Hire Me'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: custom-5107
  social-9576:
    attributes:
      css:
        class: pull-right
      btn:
        class: button-icon-clear
      title: ''
      target: _blank
      display: icons_only
      items:
        -
          icon: 'fa fa-linkedin'
          text: ''
          link: 'https://www.linkedin.com/in/eadiredja'
          name: linkedin
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/RocketTheme'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/+rockettheme'
          name: Google+
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: pintrest.com
          name: pinterest
        -
          icon: 'fa fa-youtube-play'
          text: ''
          link: ''
          name: youtube
    inherit:
      outline: default
      particle: social-3896
      include:
        - block
  custom-9276:
    title: 'Custom HTML'
    attributes:
      html: "<section class=\"expandable\">\n                <a href=\"#\" class=\"diamond\">\n                    <span class=\"background\"></span>\n                    <span class=\"line1\"></span>\n                    <span class=\"line2\"></span>\n                </a>"
    block:
      class: g-flushed
  hero-7272:
    title: 'Hero Banner'
    attributes:
      class: coverimg
      image: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/7/005/041/3e7/20df52b.jpg'
      background: 'gantry-media://savannah/hero.jpg'
      backgroundoverlay: 'gantry-media://savannah/img/overlay.png'
      htitle: 'Umo Cyrilla Eka'
      title1: 'Administrative Management'
      label1: 'Project Management & Coordination '
      title2: 'Risk Management '
      label2: 'Contract Administration'
  menu-6409:
    attributes:
      menu: savannah
      name: 'Mark '
    block:
      variations: 'nomarginall center'
  sectiontitle-6366:
    title: 'Section Title'
    attributes:
      class: ''
      title: 'Who I AM'
    block:
      variations: center
  bio-9275:
    attributes:
      name: 'Umo Cyrilla Eka'
      text: "<p>S\nelf-starter, analytical, energetic, and solutions-driven Risk Management Assistant with extensive theoretical and practical experience in the coordination of administrative activities, operations management, staff development, customer service excellence, and communications within the legal sector. Risk management and Human Resource certified team-leader with dynamic communication and organization skills, with strong administrative, writing, analytical, problems solving, and project management attributes. Proven ability to create and execute project work plans and revise as appropriate to meet changing needs and requirements, coupled with impeccable knowledge of municipal, provincial and/or federal legislation.\n<p>"
      signature: 'Umo Cyrilla Eka'
  bio-info-1264:
    title: 'Bio Stats'
    attributes:
      dob: '1983-05-29'
      phone: '289-938-6954 '
      email: Umo.Eka@gmail.com
      address: '126-201 Queen Victoria Drive Hamilton, ON, LW8 1W7 '
      social: '1'
      target: _blank
      display: icons_only
      items:
        -
          icon: 'fa fa-linkedin'
          text: ''
          link: 'https://www.linkedin.com/in/eadiredja'
          name: linkedin
        -
          icon: 'fa fa-facebook'
          text: ''
          link: facebook.com
          name: facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: twitter.com
          name: twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: plus.google.com
          name: google
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: ''
          name: pinterest
        -
          icon: 'fa fa-youtube-play'
          text: ''
          link: youtube.com
          name: youtube
  quote-7312:
    attributes:
      background: 'http://savannah-wp.tonybogdanov.com/wp-content/uploads/2014/11/parallax-cv.jpg'
      backgroundoverlay: 'gantry-media://savannah/img/overlay.png'
      text: 'Change is the law of life. And those who look only to the past or present are certain to miss the future.'
    block:
      class: g-flushed
  sectiontitle-1332:
    title: 'MY SKILLS'
    attributes:
      title: 'MY SKILLS'
    block:
      variations: center
  skillbar-5033:
    title: 'Skill Bar Graph'
    attributes:
      title: 'Interpersonal skills'
      items:
        -
          title: LeaderShip
          percent: '73'
          name: 'New item'
        -
          title: Initiative
          percent: '96'
          name: 'New item'
        -
          title: Communication
          percent: '84'
          name: 'New item'
  skillbar-4987:
    title: 'Skill Bar Graph'
    attributes:
      title: 'Soft Skills'
      items:
        -
          title: Entuhsiasm
          percent: '90'
          name: 'New item'
        -
          title: 'Team Work'
          percent: '76'
          name: 'New item'
        -
          title: Creativity
          percent: '87'
          name: 'New item'
  numcounter-9571:
    title: 'Quick Stats'
    attributes:
      items:
        -
          icon: 'fa fa-group fa-2x'
          label: Languages
          value: '2'
          name: 'New item'
        -
          icon: 'fa fa-flag fa-2x'
          label: 'Years Experience'
          value: '6'
          name: 'New item'
        -
          icon: 'fa fa-trophy fa-2x'
          label: 'Awards Won'
          value: '4'
          name: 'New item'
        -
          icon: 'fa fa-thumbs-up fa-2x'
          label: 'Volunteer Efforts'
          value: '3'
          name: 'New item'
  resumedl-6742:
    title: 'Download Resume'
    attributes:
      background: 'http://savannah-wp.tonybogdanov.com/wp-content/uploads/2014/11/parallax-cv.jpg'
      backgroundoverlay: 'gantry-media://savannah/img/overlay.png'
      title: 'Download CV'
      location: 'gantry-media://ResumeUmoEka.docx'
    block:
      class: g-flushed
      variations: center
  custom-5623:
    title: 'Custom HTML'
    attributes:
      html: "<section class=\"expandable\">\n                <a href=\"#\" class=\"diamond\">\n                    <span class=\"background\"></span>\n                    <span class=\"line1\"></span>\n                    <span class=\"line2\"></span>\n                </a>"
  sectiontitle-8251:
    title: 'WORK & EDUCATION'
    attributes:
      title: 'WORK & EDUCATION'
    block:
      variations: center
  timeline-6465:
    attributes:
      section: work
      items:
        -
          title: 'Allianz Global Assistance'
          label: 'Kitchener, ON'
          desc: 'CONTRACTS PARALEGAL'
          date: 2015-present
          name: 'New item'
        -
          title: 'Caterpillar Financial Services Ltd'
          label: 'Oakville, ON'
          desc: 'SPECIAL ACCOUNTS REPRESENTATIVE II'
          date: 2012-2014
          name: 'New item'
        -
          title: 'Professional Collection Services Ltd.'
          label: 'Hamilton, ON'
          desc: 'Manager of Legal Operations - Consultant '
          date: 2008-present
          name: 'New item'
  timeline-6997:
    attributes:
      section: education
      items:
        -
          title: 'TRIOS College'
          label: 'Hamilton, ON'
          desc: "Paralegal Diploma\n"
          date: '2005 - 2005'
          name: 'New item'
        -
          title: 'Niagara College'
          label: 'Niagara on the Lake, ON'
          desc: "\nPost Grad -Diploma, International Business Management"
          date: '2003 - 2003'
          name: 'New item'
        -
          title: 'University of Western Ontario'
          label: 'London, ON'
          desc: "\nBachelor of Arts, Political Science\n\n"
          date: '2001 - 2001'
          name: 'New item'
  sectiontitle-8933:
    title: 'Section Title'
    attributes:
      title: 'My Testimonials'
    block:
      class: g-flushed
      variations: center
  owlcarousel-7560:
    title: Testimonials
    attributes:
      variant: o2
      nav: disable
      dots: enable
      imageOverlay: '1'
      items:
        -
          image: ''
          title: Mike
          desc: 'Super good at the job and always helps.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: Bruce
          desc: 'Willing to help when the time comes and produces good results.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: Sarah
          desc: 'Such a good worker and knows about tons of stuff.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
  sectiontitle-7871:
    title: 'Section Title'
    attributes:
      class: padding-minus-tq-bottom
      title: 'Recent Readings'
    block:
      variations: center
  portfolio-3037:
    attributes:
      image: 'gantry-media://lawbook2.jpg'
      title: photp
      label: photp
    block:
      class: g-flushed
  portfolio-2986:
    attributes:
      image: 'gantry-media://savannah/article-1.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  portfolio-8825:
    attributes:
      image: 'gantry-media://savannah/edgar.jpg'
      title: title
      label: label
    block:
      class: g-flushed
  portfolio-8584:
    attributes:
      image: 'gantry-media://vr2.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  portfolio-1558:
    attributes:
      image: 'gantry-media://muhommed.jpg'
      title: titiel
      label: photo
    block:
      class: g-flushed
  portfolio-1079:
    attributes:
      image: 'gantry-media://images/article-1.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  quote-9281:
    attributes:
      background: 'http://savannah-wp.tonybogdanov.com/wp-content/uploads/2014/11/parallax-cv.jpg'
      backgroundoverlay: 'gantry-media://savannah/img/overlay.png'
      text: "There's a natural law of karma that vindictive people, who go out of their way to hurt others, will end up broke and alone.\n"
    block:
      class: g-flushed
  sectiontitle-9392:
    title: Contact
    attributes:
      title: 'Contact Me'
    block:
      variations: center
  googlemap-1641:
    title: 'Google Map'
    attributes:
      apikey: "\tAIzaSyAFd9lo4-WfB34rqre98xXZczIzxGUx_j8"
      width: 100%
      height: 358px
      maptype: ROADMAP
      latitude: '43.6278149'
      longitude: '-79.5050689'
      zoom: '15'
      defaultmarker: show
  custom-6556:
    title: 'Contact Form'
    attributes:
      html: '[contact-form-7 id="2127" title="Identity Contact form_copy"]'
      filter: '1'
  totop-8670:
    title: 'To Top'
    attributes:
      css:
        class: top
      icon: 'fa fa-chevron-up'
      content: ''
    block:
      class: g-flushed
  branding-9914:
    attributes:
      content: 'Umo Cyrilla Eka'
      css:
        class: 'colored fadeInUp animated'
    block:
      variations: 'center nomarginall nopaddingall'
  social-3503:
    attributes:
      items:
        -
          icon: 'fa fa-linkedin'
          text: ''
          link: ''
          name: Linkedin
        -
          icon: 'fa fa-facebook'
          text: ''
          link: 'http://www.facebook.com/'
          name: Facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: 'http://www.twitter.com/'
          name: Twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: 'https://plus.google.com/'
          name: Google+
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: 'https://www.pintrest.com'
          name: pintrest
        -
          icon: 'fa fa-youtube-play'
          text: ''
          link: ''
          name: Youtube
    block:
      variations: 'center nomarginall nopaddingall'
  copyright-1736:
    attributes:
      owner: 'All rights reserved.'
      additional:
        text: ''
    block:
      variations: 'center nomarginall nopaddingall'
