version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1472319055
layout:
  /intro/:
    -
      - 'custom-5989 50'
      - 'social-9576 50'
  /expandable/:
    -
      - custom-9276
  /header/:
    -
      - hero-7272
  /navigation/:
    -
      - 'menu-6409 40'
      - 'custom-9601 20'
      - 'menu-1596 40'
  /features/:
    -
      - sectiontitle-6366
    -
      - 'custom-3119 70'
      - 'bio-info-1264 30'
  /utility/:
    -
      - sectiontitle-1332
    -
      - 'skillbar-5033 33.3'
      - 'skillbar-4987 33.3'
      - 'numcounter-9571 33.3'
  /above/:
    -
      - resumedl-6742
  /expandable2/:
    -
      - custom-5623
  /expanded/:
    -
      - sectiontitle-8251
    -
      - 'timeline-6465 50'
      - 'timeline-6997 50'
  /testimonials/:
    -
      - owlcarousel-7560
  /protfolio/:
    -
      - sectiontitle-7871
    -
      - 'portfolio-3037 33.3'
      - 'portfolio-2986 33.3'
      - 'portfolio-8825 33.3'
    -
      - 'portfolio-8584 33.3'
      - 'portfolio-1558 33.3'
      - 'portfolio-1079 33.3'
  /container-main/:
    -
      -
        'mainbar 80':
          -
            - sectiontitle-9392
          -
            - 'custom-2559 50'
            - 'custom-6556 50'
          -
            - googlemap-1641
      -
        'sidebar 20': {  }
  /footer/:
    -
      - totop-8670
    -
      - branding-9914
    -
      - social-3503
    -
      - copyright-1736
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
  expandable:
    type: section
    attributes:
      boxed: '2'
      class: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  navigation:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  expandable2:
    type: section
    attributes:
      boxed: '2'
      class: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  protfolio:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  custom-5989:
    title: 'Hire Me'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: custom-5107
  social-9576:
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: social-3896
  custom-9276:
    title: 'Custom HTML'
    attributes:
      html: "<section class=\"expandable\">\n                <a href=\"#\" class=\"diamond\">\n                    <span class=\"background\"></span>\n                    <span class=\"line1\"></span>\n                    <span class=\"line2\"></span>\n                </a>"
    block:
      class: g-flushed
  hero-7272:
    title: 'Hero Banner'
    attributes:
      image: 'gantry-media://savannah/assets/cover.png'
      background: 'gantry-media://savannah/hero.jpg'
      backgroundoverlay: 'gantry-media://savannah/img/overlay.png'
      htitle: Welcome
      title1: 'BEAUTIFUL PERSON'
      label1: 'People lover'
      title2: 'Professional photographer'
      label2: 'Awesome story teller'
      title3: 'AMATEUR GUITAR PLAYER'
      label3: 'Graphic designer'
  menu-6409:
    attributes:
      menu: savannah
    block:
      variations: 'align-right nomarginall'
  custom-9601:
    title: 'Custom HTML'
    attributes:
      html: '<a href="#body" class="navbar-brand" data-animate="fadeInDown" data-delay="300"><span>Savannah May</span></a>'
    block:
      variations: 'nomarginall nopaddingall'
  menu-1596:
    attributes:
      menu: savannah-2
    block:
      variations: 'align-left nomarginall'
  sectiontitle-6366:
    title: 'Section Title'
    attributes:
      class: ''
      title: 'Who I AM'
    block:
      variations: center
  custom-3119:
    title: Features
    attributes:
      html: "\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in cididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>"
  bio-info-1264:
    title: 'Bio Stats'
    attributes:
      dob: '1981-05-11'
      phone: +12-345-6789
      email: info@savannahmay.com
      address: '1234 Str. Road, NYC, IN 567 890'
      social: '1'
      target: _blank
      display: icons_only
      items:
        -
          icon: 'fa fa-facebook'
          text: ''
          link: facebook.com
          name: Facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: twitter.com
          name: twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: plus.google.com
          name: google
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: pintrest.com
          name: pintrest
  sectiontitle-1332:
    title: 'MY SKILLS'
    attributes:
      title: 'MY SKILLS'
    block:
      variations: center
  skillbar-5033:
    title: 'Skill Bar Graph'
    attributes:
      title: skills
      items:
        -
          title: ps
          percent: '25'
          name: 'New item'
        -
          title: wp
          percent: '75'
          name: 'New item'
        -
          title: er
          percent: '68'
          name: 'New item'
  skillbar-4987:
    title: 'Skill Bar Graph'
    attributes:
      title: Skills2
      items:
        -
          title: wp
          percent: '98'
          name: 'New item'
        -
          title: photo
          percent: '78'
          name: 'New item'
        -
          title: tests
          percent: '45'
          name: 'New item'
  numcounter-9571:
    title: 'Quick Stats'
    attributes:
      items:
        -
          icon: 'fa fa-user fa-2x'
          label: 'Happy Clients'
          value: '150'
          name: 'New item'
        -
          icon: 'fa fa-user fa-2x'
          label: 'Year Experience'
          value: '7'
          name: 'New item'
        -
          icon: 'fa fa-user fa-2x'
          label: 'Awards Won'
          value: '13'
          name: 'New item'
        -
          icon: 'fa fa-user fa-2x'
          label: 'Projects Done'
          value: '520'
          name: 'New item'
  resumedl-6742:
    title: 'Download Resume'
    attributes:
      title: 'Download CV'
      location: ''
    block:
      variations: center
  custom-5623:
    title: 'Custom HTML'
    attributes:
      html: "<section class=\"expandable\">\n                <a href=\"#\" class=\"diamond\">\n                    <span class=\"background\"></span>\n                    <span class=\"line1\"></span>\n                    <span class=\"line2\"></span>\n                </a>"
  sectiontitle-8251:
    title: 'WORK & EDUCATION'
    attributes:
      title: 'WORK & EDUCATION'
    block:
      variations: center
  timeline-6465:
    attributes:
      section: work
      items:
        -
          section: present
          title: 'LEAD PHOTOGRAPHER'
          label: 'FOTOSHOOT MAGAZINE'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-04
          enddate: 2016-11
          current: 'yes'
          name: 'New item'
        -
          section: present
          title: 'JUNIOR PHOTOGRAPHER'
          label: 'ABC MODEL AGENCY'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2015-07
          enddate: 2016-06
          current: 'no'
          name: 'New item'
        -
          section: present
          title: 'GRAPHIC DESIGNER'
          label: 'FXMEDIA LTD.'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2010-09
          enddate: 2013-09
          current: 'no'
          name: 'New item'
  timeline-6997:
    attributes:
      section: education
      items:
        -
          section: education
          title: 'GRAPHIC DESIGNER'
          label: 'FXMEDIA LTD.'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
        -
          section: education
          title: 'MASTERS DEGREE HARVARD'
          label: 'ART HISTORY'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
        -
          section: education
          title: 'BACHELORS DEGREE HARVARD'
          label: 'PHOTOGRAPHY & DESIGN'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
  owlcarousel-7560:
    title: 'Owl Carousel'
    attributes:
      nav: disable
      dots: enable
      imageOverlay: disable
      items:
        -
          image: ''
          title: 'Jon Doe'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: Tommy
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: Jane
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
  sectiontitle-7871:
    title: 'Section Title'
    attributes:
      class: padding
      title: PORTFOLIO
    block:
      variations: center
  portfolio-3037:
    attributes:
      image: 'gantry-media://savannah/edgar.jpg'
      title: photp
      label: photp
    block:
      class: g-flushed
  portfolio-2986:
    attributes:
      image: 'gantry-media://savannah/edgar.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  portfolio-8825:
    attributes:
      image: 'gantry-media://savannah/edgar.jpg'
      title: title
      label: label
    block:
      class: g-flushed
  portfolio-8584:
    attributes:
      image: 'gantry-media://muhommed.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  portfolio-1558:
    attributes:
      image: 'gantry-media://savannah/trump.JPG'
      title: titiel
      label: photo
    block:
      class: g-flushed
  portfolio-1079:
    attributes:
      image: 'gantry-media://muhommed.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  sectiontitle-9392:
    title: Contact
    attributes:
      title: Contacts
    block:
      variations: center
  custom-2559:
    title: 'Custom HTML'
    attributes:
      html: '<iframe class="map" src="http://maps.google.com/maps?f=q&source=s_q&hl=en&q=Adobe%20Systems%20Inc%2C%20Park%20Avenue%2C%20San%20Jose%2C%20CA&aq=0&ie=UTF8&t=m&z=12&iwloc=&output=embed"></iframe>'
  custom-6556:
    title: 'Contact Form'
    attributes:
      html: '[contact-form-7 id="2127" title="Identity Contact form_copy"]'
      filter: '1'
  googlemap-1641:
    title: 'Google Map'
    attributes:
      enabled: 0
      apikey: AIzaSyBHIiVSvNxaEm6AE8a3vFS7yXk1RixnX6Q
      height: 100%
      maptype: ROADMAP
      latitude: '52.052312'
      longitude: '4.447141'
      zoom: '7'
      defaultmarker: show
      dragging: disabledmobile
  totop-8670:
    title: 'To Top'
    attributes:
      css:
        class: top
      icon: 'fa fa-chevron-up'
      content: ''
    block:
      class: g-flushed
  branding-9914:
    attributes:
      content: 'SAVANNAH MAY'
      css:
        class: 'colored fadeInUp animated'
    block:
      variations: 'center nomarginall nopaddingall'
  social-3503:
    attributes:
      items:
        -
          icon: 'fa fa-facebook'
          text: ''
          link: 'http://www.facebook.com/'
          name: Facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: 'http://www.twitter.com/'
          name: Twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: 'https://plus.google.com/'
          name: Google+
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: 'https://www.pintrest.com'
          name: pintrest
    block:
      variations: 'center nomarginall nopaddingall'
  copyright-1736:
    attributes:
      owner: 'All rights reserved.'
      additional:
        text: ''
    block:
      variations: 'center nomarginall nopaddingall'
