version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1472319055
layout:
  /intro/:
    -
      - 'custom-5989 50'
      - 'social-9576 50'
  /expandable/:
    -
      - custom-9276
  /header/:
    -
      - hero-7272
  /navigation/:
    -
      - menu-6409
  /features/:
    -
      - sectiontitle-6366
    -
      - 'custom-3119 70'
      - 'bio-info-1264 30'
  /quote/:
    -
      - 'custom-2861 20'
      - 'custom-6100 60'
      - 'custom-4505 20'
  /utility/:
    -
      - sectiontitle-1332
    -
      - 'skillbar-5033 33.3'
      - 'skillbar-4987 33.3'
      - 'numcounter-9571 33.3'
  /above/:
    -
      - resumedl-6742
  /expandable2/:
    -
      - custom-5623
  /expanded/:
    -
      - sectiontitle-8251
    -
      - 'timeline-6465 50'
      - 'timeline-6997 50'
  /testimonials/:
    -
      - sectiontitle-8933
    -
      - owlcarousel-7560
  /portfolio/:
    -
      - sectiontitle-7871
    -
      - 'spacer-9583 14'
      - 'portfolio-3037 24'
      - 'portfolio-2986 24'
      - 'portfolio-8825 24'
      - 'spacer-1143 14'
    -
      - 'spacer-6966 14'
      - 'portfolio-8584 24'
      - 'portfolio-1558 24'
      - 'portfolio-1079 24'
      - 'spacer-9951 14'
  /container-main/:
    -
      -
        'mainbar 80':
          -
            - sectiontitle-9392
          -
            - 'googlemap-1641 50'
            - 'custom-6556 50'
      -
        'sidebar 20': {  }
  /footer/:
    -
      - totop-8670
    -
      - branding-9914
    -
      - social-3503
    -
      - copyright-1736
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
  expandable:
    type: section
    attributes:
      boxed: '2'
      class: ''
  header:
    attributes:
      boxed: ''
      class: g-flushed
  navigation:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  quote:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  expandable2:
    type: section
    attributes:
      boxed: '2'
      class: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  custom-5989:
    title: 'Hire Me'
    inherit:
      outline: default
      include:
        - attributes
        - block
      particle: custom-5107
  social-9576:
    attributes:
      css:
        class: pull-right
      btn:
        class: button-icon-clear
      title: ''
      target: _blank
      display: icons_only
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/RocketTheme'
          name: Facebook
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/+rockettheme'
          name: Google+
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: pintrest.com
          name: 'New item'
        -
          icon: 'fa fa-linkedin'
          text: ''
          link: dribbble.com
          name: 'New item'
    inherit:
      outline: default
      particle: social-3896
      include:
        - block
  custom-9276:
    title: 'Custom HTML'
    attributes:
      html: "<section class=\"expandable\">\n                <a href=\"#\" class=\"diamond\">\n                    <span class=\"background\"></span>\n                    <span class=\"line1\"></span>\n                    <span class=\"line2\"></span>\n                </a>"
    block:
      class: g-flushed
  hero-7272:
    title: 'Hero Banner'
    attributes:
      class: coverimg
      image: 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/7/005/045/066/344c078.jpg'
      background: 'gantry-media://savannah/hero.jpg'
      backgroundoverlay: 'gantry-media://savannah/img/overlay.png'
      htitle: Welcome
      title1: 'BEAUTIFUL PERSON'
      label1: 'People lover'
      title2: 'Professional photographer'
      label2: 'Awesome story teller'
      title3: 'AMATEUR GUITAR PLAYER'
      label3: 'Graphic designer'
  menu-6409:
    attributes:
      menu: savannah
      name: 'Savannah May'
    block:
      variations: 'nomarginall center'
  sectiontitle-6366:
    title: 'Section Title'
    attributes:
      class: ''
      title: 'Who I AM'
    block:
      variations: center
  custom-3119:
    title: Features
    attributes:
      html: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam aliquam eros diam, eu lobortis velit elementum aliquam. Fusce diam mi, tempor id lectus a, pulvinar tincidunt libero. Morbi sapien nulla, venenatis eget neque quis, commodo dictum urna. Vestibulum libero felis, accumsan nec vehicula at, tristique in mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam gravida leo a sapien gravida ornare. Aenean fringilla tincidunt ipsum ut cursus. Pellentesque tincidunt, risus nec ultricies laoreet, felis mi bibendum eros, nec efficitur purus diam a sem. Aliquam cursus sed felis in molestie. Mauris cursus odio sit amet quam mattis placerat.</p>\n<p>\nSed tellus nisl, feugiat bibendum mattis ut, vulputate et dolor. Suspendisse potenti. Cras at facilisis leo, eget dignissim eros. Nunc at ultricies diam, sed vehicula odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam vulputate, ex eu dictum aliquam, lectus est fringilla nisi, ut hendrerit augue turpis malesuada erat. Pellentesque habitant morbi tristique senectus.<p>"
  bio-info-1264:
    title: 'Bio Stats'
    attributes:
      dob: '1981-05-11'
      phone: +12-345-6789
      email: info@savannahmay.com
      address: '1234 Str. Road, NYC, IN 567 890'
      social: '1'
      target: _blank
      display: icons_only
      items:
        -
          icon: 'fa fa-facebook'
          text: ''
          link: facebook.com
          name: facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: twitter.com
          name: twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: plus.google.com
          name: google
        -
          icon: 'fa fa-youtube-play'
          text: ''
          link: youtube.com
          name: youtube
        -
          icon: 'fa fa-linkedin'
          text: ''
          link: linkedin.com
          name: linkedin
  custom-2861:
    title: 'Custom HTML'
    attributes:
      html: '<i class="fa fa-2x fa-quote-right fa-flip-horizontal" aria-hidden="true"></i>'
    block:
      variations: align-right
  custom-6100:
    title: 'Custom HTML'
    attributes:
      html: '<h4>It''s the repletion of affirmations that leads to belief becomes a deep conviction, things begin to happen</h4>'
  custom-4505:
    title: 'Custom HTML'
    attributes:
      html: '<i class="fa fa-2x fa-quote-right" aria-hidden="true"></i>'
    block:
      variations: align-left
  sectiontitle-1332:
    title: 'MY SKILLS'
    attributes:
      title: 'MY SKILLS'
    block:
      variations: center
  skillbar-5033:
    title: 'Skill Bar Graph'
    attributes:
      title: 'Interpersonal skills'
      items:
        -
          title: LeaderShip
          percent: '70'
          name: 'New item'
        -
          title: Initiative
          percent: '75'
          name: 'New item'
        -
          title: Communication
          percent: '80'
          name: 'New item'
  skillbar-4987:
    title: 'Skill Bar Graph'
    attributes:
      title: 'Soft Skills'
      items:
        -
          title: Entuhsiasm
          percent: '98'
          name: 'New item'
        -
          title: 'Team Work'
          percent: '78'
          name: 'New item'
        -
          title: Creativity
          percent: '85'
          name: 'New item'
  numcounter-9571:
    title: 'Quick Stats'
    attributes:
      items:
        -
          icon: 'fa fa-group fa-2x'
          label: Languages
          value: '3'
          name: 'New item'
        -
          icon: 'fa fa-flag fa-2x'
          label: 'Years Experience'
          value: '7'
          name: 'New item'
        -
          icon: 'fa fa-trophy fa-2x'
          label: 'Awards Won'
          value: '13'
          name: 'New item'
        -
          icon: 'fa fa-thumbs-up fa-2x'
          label: 'Volunteer Efforts'
          value: '10'
          name: 'New item'
  resumedl-6742:
    title: 'Download Resume'
    attributes:
      title: 'Download CV'
      location: ''
    block:
      variations: center
  custom-5623:
    title: 'Custom HTML'
    attributes:
      html: "<section class=\"expandable\">\n                <a href=\"#\" class=\"diamond\">\n                    <span class=\"background\"></span>\n                    <span class=\"line1\"></span>\n                    <span class=\"line2\"></span>\n                </a>"
  sectiontitle-8251:
    title: 'WORK & EDUCATION'
    attributes:
      title: 'WORK & EDUCATION'
    block:
      variations: center
  timeline-6465:
    attributes:
      section: work
      items:
        -
          section: present
          title: 'LEAD PHOTOGRAPHER'
          label: 'FOTOSHOOT MAGAZINE'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-04
          enddate: 2016-11
          current: 'yes'
          name: 'New item'
        -
          section: present
          title: 'JUNIOR PHOTOGRAPHER'
          label: 'ABC MODEL AGENCY'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2015-07
          enddate: 2016-06
          current: 'no'
          name: 'New item'
        -
          section: present
          title: 'GRAPHIC DESIGNER'
          label: 'FXMEDIA LTD.'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2010-09
          enddate: 2013-09
          current: 'no'
          name: 'New item'
  timeline-6997:
    attributes:
      section: education
      items:
        -
          section: education
          title: 'GRAPHIC DESIGNER'
          label: 'FXMEDIA LTD.'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
        -
          section: education
          title: 'MASTERS DEGREE HARVARD'
          label: 'ART HISTORY'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
        -
          section: education
          title: 'BACHELORS DEGREE HARVARD'
          label: 'PHOTOGRAPHY & DESIGN'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
  sectiontitle-8933:
    title: 'Section Title'
    attributes:
      title: 'My Testimonials'
    block:
      class: g-flushed
      variations: center
  owlcarousel-7560:
    title: 'Owl Carousel'
    attributes:
      variant: o2
      nav: disable
      dots: enable
      items:
        -
          image: ''
          title: 'Jon Doe'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: Tommy
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
        -
          image: ''
          title: Jane
          desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'New item'
  sectiontitle-7871:
    title: 'Section Title'
    attributes:
      class: padding-minus-tq-bottom
      title: PORTFOLIO
    block:
      variations: center
  portfolio-3037:
    attributes:
      image: 'gantry-media://savannah/edgar.jpg'
      title: photp
      label: photp
    block:
      class: g-flushed
  portfolio-2986:
    attributes:
      image: 'gantry-media://savannah/edgar.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  portfolio-8825:
    attributes:
      image: 'gantry-media://savannah/edgar.jpg'
      title: title
      label: label
    block:
      class: g-flushed
  portfolio-8584:
    attributes:
      image: 'gantry-media://muhommed.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  portfolio-1558:
    attributes:
      image: 'gantry-media://muhommed.jpg'
      title: titiel
      label: photo
    block:
      class: g-flushed
  portfolio-1079:
    attributes:
      image: 'gantry-media://muhommed.jpg'
      title: title
      label: photo
    block:
      class: g-flushed
  sectiontitle-9392:
    title: Contact
    attributes:
      title: 'Contact Me'
    block:
      variations: center
  googlemap-1641:
    title: 'Google Map'
    attributes:
      apikey: AIzaSyAFd9lo4-WfB34rqre98xXZczIzxGUx_j8
      width: 100%
      height: 358px
      maptype: ROADMAP
      latitude: '43.6278149'
      longitude: '-79.5050689'
      zoom: '15'
      defaultmarker: show
  custom-6556:
    title: 'Contact Form'
    attributes:
      html: '[contact-form-7 id="2127" title="Identity Contact form_copy"]'
      filter: '1'
  totop-8670:
    title: 'To Top'
    attributes:
      css:
        class: top
      icon: 'fa fa-chevron-up'
      content: ''
    block:
      class: g-flushed
  branding-9914:
    attributes:
      content: 'SAVANNAH MAY'
      css:
        class: 'colored fadeInUp animated'
    block:
      variations: 'center nomarginall nopaddingall'
  social-3503:
    attributes:
      items:
        -
          icon: 'fa fa-facebook'
          text: ''
          link: 'http://www.facebook.com/'
          name: Facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: 'http://www.twitter.com/'
          name: Twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: 'https://plus.google.com/'
          name: Google+
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: 'https://www.pintrest.com'
          name: pintrest
    block:
      variations: 'center nomarginall nopaddingall'
  copyright-1736:
    attributes:
      owner: 'All rights reserved.'
      additional:
        text: ''
    block:
      variations: 'center nomarginall nopaddingall'
