version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1472319055
layout:
  intro: {  }
  /header/:
    -
      - owlcarousel-2455
  /navigation/:
    -
      - 'menu-6409 40'
      - 'custom-9601 20'
      - 'menu-1596 40'
  /features/:
    -
      - sectiontitle-6366
    -
      - 'custom-3119 70'
      - 'bio-info-1264 30'
  /utility/:
    -
      - sectiontitle-1332
    -
      - 'skillbar-5033 33.3'
      - 'skillbar-4987 33.3'
      - 'skillbar-2594 33.3'
  /above/:
    -
      - resumedl-6742
  /expanded/:
    -
      - sectiontitle-8251
    -
      - timeline-6465
  /testimonials/:
    -
      - owlcarousel-7560
  /protfolio/:
    -
      - sectiontitle-7871
    -
      - isotope-8736
  /container-main/:
    -
      -
        'mainbar 80':
          -
            - sectiontitle-9392
          -
            - 'custom-7545 50'
            - 'custom-6556 50'
      -
        'sidebar 20': {  }
  /footer/:
    -
      - totop-8670
    -
      - branding-9914
    -
      - social-3503
    -
      - copyright-1736
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
  navigation:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  protfolio:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      imageOverlay: disable
      items:
        -
          image: 'gantry-media://savannah/hero.jpg'
          title: 'Savannah is here!'
          desc: 'Begin your journey with a brand new &raquo;free&laquo; Gantry 5 template from RocketTheme.'
          link: 'http://gantry.org/downloads'
          linktext: ''
          buttonclass: ''
          name: 'Item 1'
        -
          image: 'gantry-media://header/img02.jpg'
          title: 'Savannah is Gantry powered!'
          desc: 'Savannah is based on the powerful Gantry framework.'
          link: 'http://gantry.org/downloads'
          linktext: 'Download Now'
          buttonclass: button-outline
          name: 'Item 2'
  menu-6409:
    attributes:
      menu: savannah
    block:
      variations: align-right
  custom-9601:
    title: 'Custom HTML'
    attributes:
      html: '<a href="#body" class="navbar-brand" data-animate="fadeInDown" data-delay="300"><span>Savannah May</span></a>'
  menu-1596:
    attributes:
      menu: savannah-2
    block:
      variations: align-left
  sectiontitle-6366:
    title: 'Section Title'
    attributes:
      class: ''
      title: 'Who I AM'
  custom-3119:
    title: Features
    attributes:
      html: "\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in cididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>"
  bio-info-1264:
    title: 'Bio Stats'
    attributes:
      dob: '1981-05-11'
      phone: +12-345-6789
      email: info@savannahmay.com
      address: '1234 Str. Road, NYC, IN 567 890'
      social: '1'
      target: _blank
      display: icons_only
      items:
        -
          icon: 'fa fa-facebook'
          text: ''
          link: facebook.com
          name: Facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: twitter.com
          name: twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: plus.google.com
          name: google
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: pintrest.com
          name: pintrest
  sectiontitle-1332:
    title: 'Section Title'
  skillbar-5033:
    title: 'Skill Bar Graph'
  skillbar-4987:
    title: 'Skill Bar Graph'
  skillbar-2594:
    title: 'Skill Bar Graph'
  resumedl-6742:
    title: 'Download Resume'
    attributes:
      title: 'Download CV'
      location: ''
  sectiontitle-8251:
    title: 'Section Title'
  owlcarousel-7560:
    title: 'Owl Carousel'
  sectiontitle-7871:
    title: 'Section Title'
  isotope-8736:
    title: Portfolio
  sectiontitle-9392:
    title: Contact
  custom-7545:
    title: 'Custom HTML'
    attributes:
      html: Map
  custom-6556:
    title: 'Contact Form'
    attributes:
      html: '[contact-form-7 id="12" title="Contact form 1"]'
  totop-8670:
    title: 'To Top'
  branding-9914:
    attributes:
      content: 'SAVANNAH MAY'
  social-3503:
    attributes:
      items:
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/'
          name: Facebook
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/'
          name: Twitter
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/'
          name: Google+
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: 'https://www.pintrest.com'
          name: pintrest
