version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1472319055
layout:
  intro: {  }
  /header/:
    -
      - owlcarousel-2455
  /navigation/:
    -
      - 'menu-6409 40'
      - 'custom-9601 20'
      - 'menu-1596 40'
  /features/:
    -
      - sectiontitle-6366
    -
      - 'custom-3119 70'
      - 'bio-info-1264 30'
  /utility/:
    -
      - sectiontitle-1332
    -
      - 'skillbar-5033 33.3'
      - 'skillbar-4987 33.3'
      - 'numcounter-9571 33.3'
  /above/:
    -
      - resumedl-6742
  /expanded/:
    -
      - sectiontitle-8251
    -
      - 'timeline-6465 50'
      - 'timeline-6997 50'
  /testimonials/:
    -
      - owlcarousel-7560
  /protfolio/:
    -
      - sectiontitle-7871
    -
      - isotope-8736
  /container-main/:
    -
      -
        'mainbar 80':
          -
            - sectiontitle-9392
          -
            - 'custom-2559 50'
            - 'custom-6556 50'
          -
            - googlemap-1641
      -
        'sidebar 20': {  }
  /footer/:
    -
      - totop-8670
    -
      - branding-9914
    -
      - social-3503
    -
      - copyright-1736
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  intro:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
  navigation:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  protfolio:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      imageOverlay: disable
      items:
        -
          image: 'gantry-media://savannah/hero.jpg'
          title: 'Savannah is here!'
          desc: 'Begin your journey with a brand new &raquo;free&laquo; Gantry 5 template from RocketTheme.'
          link: 'http://gantry.org/downloads'
          linktext: ''
          buttonclass: ''
          name: 'Item 1'
        -
          image: 'gantry-media://header/img02.jpg'
          title: 'Savannah is Gantry powered!'
          desc: 'Savannah is based on the powerful Gantry framework.'
          link: 'http://gantry.org/downloads'
          linktext: 'Download Now'
          buttonclass: button-outline
          name: 'Item 2'
  menu-6409:
    attributes:
      menu: savannah
    block:
      variations: align-right
  custom-9601:
    title: 'Custom HTML'
    attributes:
      html: '<a href="#body" class="navbar-brand" data-animate="fadeInDown" data-delay="300"><span>Savannah May</span></a>'
  menu-1596:
    attributes:
      menu: savannah-2
    block:
      variations: align-left
  sectiontitle-6366:
    title: 'Section Title'
    attributes:
      class: ''
      title: 'Who I AM'
    block:
      variations: center
  custom-3119:
    title: Features
    attributes:
      html: "\t\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor in cididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>\n<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>"
  bio-info-1264:
    title: 'Bio Stats'
    attributes:
      dob: '1981-05-11'
      phone: +12-345-6789
      email: info@savannahmay.com
      address: '1234 Str. Road, NYC, IN 567 890'
      social: '1'
      target: _blank
      display: icons_only
      items:
        -
          icon: 'fa fa-facebook'
          text: ''
          link: facebook.com
          name: Facebook
        -
          icon: 'fa fa-twitter'
          text: ''
          link: twitter.com
          name: twitter
        -
          icon: 'fa fa-google-plus'
          text: ''
          link: plus.google.com
          name: google
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: pintrest.com
          name: pintrest
  sectiontitle-1332:
    title: 'MY SKILLS'
    attributes:
      title: 'MY SKILLS'
    block:
      variations: center
  skillbar-5033:
    title: 'Skill Bar Graph'
    attributes:
      title: skills
      items:
        -
          title: ps
          percent: '25'
          name: 'New item'
        -
          title: wp
          percent: '75'
          name: 'New item'
        -
          title: er
          percent: '68'
          name: 'New item'
  skillbar-4987:
    title: 'Skill Bar Graph'
    attributes:
      title: Skills2
      items:
        -
          title: wp
          percent: '98'
          name: 'New item'
        -
          title: photo
          percent: '78'
          name: 'New item'
        -
          title: tests
          percent: '45'
          name: 'New item'
  numcounter-9571:
    title: 'Quick Stats'
    attributes:
      items:
        -
          icon: 'fa fa-user fa-2x'
          label: 'Happy Clients'
          value: '150'
          name: 'New item'
        -
          icon: 'fa fa-user fa-2x'
          label: 'Year Experience'
          value: '7'
          name: 'New item'
        -
          icon: 'fa fa-user fa-2x'
          label: 'Awards Won'
          value: '13'
          name: 'New item'
        -
          icon: 'fa fa-user fa-2x'
          label: 'Projects Done'
          value: '520'
          name: 'New item'
  resumedl-6742:
    title: 'Download Resume'
    attributes:
      title: 'Download CV'
      location: ''
    block:
      variations: center
  sectiontitle-8251:
    title: 'WORK & EDUCATION'
    attributes:
      title: 'WORK & EDUCATION'
    block:
      variations: center
  timeline-6465:
    attributes:
      section: work
      items:
        -
          section: present
          title: 'LEAD PHOTOGRAPHER'
          label: 'FOTOSHOOT MAGAZINE'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-04
          enddate: 2016-11
          current: 'yes'
          name: 'New item'
        -
          section: present
          title: 'JUNIOR PHOTOGRAPHER'
          label: 'ABC MODEL AGENCY'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2015-07
          enddate: 2016-06
          current: 'no'
          name: 'New item'
        -
          section: present
          title: 'GRAPHIC DESIGNER'
          label: 'FXMEDIA LTD.'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2010-09
          enddate: 2013-09
          current: 'no'
          name: 'New item'
  timeline-6997:
    attributes:
      section: education
      items:
        -
          section: education
          title: 'GRAPHIC DESIGNER'
          label: 'FXMEDIA LTD.'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
        -
          section: education
          title: 'MASTERS DEGREE HARVARD'
          label: 'ART HISTORY'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
        -
          section: education
          title: 'BACHELORS DEGREE HARVARD'
          label: 'PHOTOGRAPHY & DESIGN'
          desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.'
          startdate: 2016-11
          enddate: 2016-11
          current: 'no'
          name: 'New item'
  owlcarousel-7560:
    title: 'Owl Carousel'
  sectiontitle-7871:
    title: 'Section Title'
    attributes:
      class: ''
      title: PORTFOLIO
    block:
      variations: center
  isotope-8736:
    title: Portfolio
  sectiontitle-9392:
    title: Contact
    attributes:
      title: Contacts
    block:
      variations: center
  custom-2559:
    title: 'Custom HTML'
    attributes:
      html: "<div id=\"map\"></div>\n    <script>\n      var map;\n      function initMap() {\n        map = new google.maps.Map(document.getElementById('map'), {\n          center: {lat: -34.397, lng: 150.644},\n          zoom: 8\n        });\n      }\n    </script>\n    <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBHIiVSvNxaEm6AE8a3vFS7yXk1RixnX6Q&callback=initMap\"\n    async defer></script>"
  custom-6556:
    title: 'Contact Form'
    attributes:
      html: '[contact-form-7 id="2127" title="Identity Contact form_copy"]'
      filter: '1'
  googlemap-1641:
    title: 'Google Map'
    attributes:
      enabled: 0
      apikey: AIzaSyBHIiVSvNxaEm6AE8a3vFS7yXk1RixnX6Q
      height: 100%
      maptype: ROADMAP
      latitude: '52.052312'
      longitude: '4.447141'
      zoom: '7'
      defaultmarker: show
      dragging: disabledmobile
  totop-8670:
    title: 'To Top'
  branding-9914:
    attributes:
      content: 'SAVANNAH MAY'
  social-3503:
    attributes:
      items:
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/'
          name: Facebook
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/'
          name: Twitter
        -
          icon: 'fa fa-google-plus fa-fw'
          text: ''
          link: 'https://plus.google.com/'
          name: Google+
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: 'https://www.pintrest.com'
          name: pintrest
