name: home
timestamp: 1479245052
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home
  timestamp: 1472319055
positions: {  }
sections:
  intro: Intro
  navigation: Navigation
  features: Features
  utility: Utility
  above: Above
  expanded: Expanded
  testimonials: Testimonials
  protfolio: Protfolio
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  custom:
    custom-5807: Intro
  widget:
    position-widget-2899: Widget
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  logo:
    logo-9608: 'Logo / Image'
    logo-9571: 'Logo / Image'
  menu:
    menu-6409: Menu
  social:
    social-3171: Social
  copyright:
    copyright-1736: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
